@startuml
'https://plantuml.com/state-diagram
Title TIE Interceptor 

state Idle
state Fight
state c <<choice>>
state Maintenance

[*] -> Idle : scenario start
Idle --> Fight : new Fight()

Fight -> c : fight.hp > 0
c -> Maintenance : true
c -> Fight : false

Maintenance -> Idle : onRepairFinish()

Idle -> [*] : scenario end

@enduml