@startuml
'https://plantuml.com/state-diagram
Title TIE Shuttle 

state Idle
state Embark
state Transport
state Disembark
state Maintenance

[*] -> Idle : scenario start 
Idle -d-> Embark : enough clients to leave
Embark -d-> Transport : capacity full
Transport -> Disembark : arrived at destination
Disembark -u-> Maintenance : capacity empty
Maintenance -u-> Idle : finished repairs 
Idle -> [*] : scenario end

@enduml