@startuml


package Models {
    ' ----------------------------------- '
    ' -- Enum                          -- '
    ' Red = Rescue
    ' Yellow = Fires
    ' Blue = Cargo
    ' Green = Passenger
    ' Gray = Observer
    enum Colour {
        RED
        YELLOW
        BLUE
        GREEN
        GRAY
    }

    class Position {
        - _x: int
        - _y: int
        + Position(int x, int y)
        + Position(string longitude, string latitude)
        + {static} Transpose(int x, int y): string
        + {static} Transpose(string): Tuple<int, int>
        + ToString(): string
    }

    class Scenario << (S, Orange) Singleton >> {
        - _airports: List<Airport>
        - _tasks: List<Task>
        - _unassignedTasks: List<Task>
        - {static} _scenario: Scenario
        + {static} GetScenario(): Scenario
        + GenerateTasks(): void
        + HandleTick(double time): void
        + RemoveTask(Task task): void
        + GetNearestAirports(Position position): List<Airport>
    }
    
    ' -----------------------------------'
    ' -- Airport Management           -- '
    package "Airplanes and Airports" {
        class Airport {
            - _id: string
            - _name: string
            - _position: Position
            - _airplanes: List<Airplane>
            - _passengerTraffic: int
            - _merchandiseTraffic: double
            - _clients : List<TaskTransport>
            + Action(double time): double
            + AssignTask(Task task): bool
        }
    
        abstract class Airplane {
            - _id: string
            - _name: string
            - _speed: int
            - _maintenanceTime: int
            - _origin: Airport
            - _colour: Colour 
            - _state: IState
            + Action(double time): double
            + AssignTask(Task task): bool
            + ChangeState(): void
            + ChangeState(Task task): void
        }

        class FightPlane extends Airplane{
            + AssignTask(Task task): bool
            + ChangeState(): void
        }
        
        abstract class TransportPlane extends Airplane {
            - _maxCapacity: double
            - _embarkingTime: int
            - _disembarkingTime: int
            + AssignTask(Task task): bool
            + ChangeState(): void
            + ChangeState(Task task): void
        }
        
        class PassengerPlane extends TransportPlane {
        }
        
        class MerchandisePlane extends TransportPlane {
        }
        
        class ScoutPlane extends Airplane{
            + AssignTask(Task task): bool
            + ChangeState(): void
        }
        
        class RescuePlane extends Airplane{
            + AssignTask(Task task): bool
            + ChangeState(): void
        }
    }
    
    ' -----------------------------------'
    ' -- Airplane States              -- '
    
    package "Airplane States" {
        interface IState {
            + Action(double time): double
        }
        
        abstract class StateWithPlane implements IState {
            - _plane: Airplane
        }
        
        abstract class FlyingState extends StateWithPlane implements ITaskState {
            - _current: Position
            - _destination: Position
            - CalculateDistance(Position current, Position destination): Position
            + Action(double time): double
        }
        
        class StandbyState implements IState {
            + Action(double time): double
        }
        
        interface ITaskState extends IState {
            # Task : Task
        }
        
        abstract TimedState extends StateWithPlane{
            - _time : double
            + Action(double time): double
        }
        
        class MaintenanceState extends TimedState {
        }
        
        abstract class TimedStateWithTask extends TimedState implements ITaskState {
        }
        
        class EmbarkState extends TimedStateWithTask {
        }
        
        class DisembarkState extends TimedStateWithTask {
        }
        
        class TransportFlight extends FlyingState {
            - _capacity : double
            + Action(double time): double
        }
        
        class FightingFlight extends FlyingState {
            + Action(double time): double
        }
        
        class RescueFlight extends FlyingState {
            + Action(double time): double
        }
        
        class ScoutFlight extends FlyingState {
            + Action(double time): double
        }
    }
    
    ' ---------------------------------- '
    ' -- Tasks Management            -- '
    package Task {
        class TaskFactory << (S,orange) Singleton>> {
            - {static} _instance: TaskFactory
            + {static} GetInstance(): TaskFactory
            + GenerateFight(): TaskFight
            + GenerateRescue(): TaskRescue
            + GeneratePassengers(): ClientPassenger
            + GenerateMerchandise(): ClientMerchandise
            + GenerateScout(): TaskScout
            - GetRandomPosition(): Position
        }

        abstract class Task {
            - _position : Position
            + ToString() : string
            + HandleTask() : void
            - GenerateRandomPosition : Position
        }

        abstract class TaskTransport extends Task {
            - _destination : Airport
        }

        together {
            class ClientPassenger extends TaskTransport {
                - _count: int
            }

            class ClientMerchandise extends TaskTransport {
                - _count: double
            }
        }

        class TaskRescue extends Task {
        }

        class TaskScout extends Task {
        }

        class TaskFight extends Task {
            + HandleTask() : void
            - _force: int
        }
    }
}

package Controllers {
    class Simulator << (S,orange) Singleton>> {
        - _simulator: Simulator
        - _view : FormMap
        - {static} _instance: Scenario
        + {static} Instance(): Scenario 
        + {static} Main(): void
        + LoadScenario(): void
        + OnTick(double time): void
    }
}

package Views {
    class FormMap {
    }
}

' Relations
' - Global
' -- Controller and View
Simulator "1" *-u-> "1" FormMap
FormMap -d-> Simulator
' -- Controller and Model
Simulator "1" *--> "1" Scenario
Simulator "1" *-> "1" Simulator

' - Model
' -- Scenario
Scenario -d-> TaskFactory
Scenario "1" *--> "1" Scenario
Scenario "1" *-d-> "N" Task
Scenario "1" *-l-> "N" Airport

' -- Airport
Airport "1" *--> "N" Airplane
Airport "1" o-> "N" TaskTransport

' -- Airplane
Airplane "1" o---d-> "1" IState
Airplane "1" o--> "1" Airport

' -- Tasks
TaskFactory --> Task
TaskFactory "1" *--> "1" TaskFactory
ITaskState "1" o--> "1" Task

TaskTransport "1" o-> "1" Airport
Task <.. Airport
Task <.. Airplane
Task -u-> Scenario
   
@enduml