@startuml Adding plane to airport
title Adding a plane into an airport

actor User

User -> FormGenerator ++: btnAddAirplane_Click(object sender, EventArgs e)

' Get all airplaine Info
FormGenerator -> FormGenerator ++: IsAirplaneValid()
return true
FormGenerator -> FormGenerator ++: GetAirplaneType(string type)
return AirplaneType
FormGenerator -> FormGenerator ++: GetAirplaneInfo(AirplaneType type)
FormGenerator -> AirplaneInfo ++: new AirplaneInfo(string id, string name, AirplaneType type, int speed, int maintenanceTime)
return AirplaneInfo
return AirplaneInfo

'Create airplane
FormGenerator -> Generator ++: AddAiplane(string airportId, AirplaneInfo info)
Generator -> Scenario ++: AddAirplane(string airportId, AirplaneInfo info)

'If airplane exists
Scenario -> Scenario ++: HasAirplane(string airplaneId)
Scenario -> Scenario ++: GetAirportWithPlane(string airplaneCode)
group For each airport 
    Scenario -> Airport ++: HasPlane(string airplaneCode)
    return false
end
return null
return false

'Add airplane to airport
Scenario -> Scenario ++: GetAirport(string airportCode)
return Airport

Scenario -> Airport ++: AddAirplane(AirplaneInfo data)
Airport -> AirplaneFactory ++: CreateAirplane(AirplaneInfo data)
AirplaneFactory -> Airplane ++: new Airplane(AirplaneInfo data)
return Airplane
return Airplane
return
return

' Update airplanes 
Generator -> Generator ++: UpdateAirplanes(string airportId)

'Get all airplanes
Generator -> Scenario ++: GetAirplanesInfo(string airportId)
Scenario ->  Scenario ++: GetAirport(string airportCode)
return Airport

Scenario -> Airport ++: GetAirplanesInfo()
Airport -> Airplane ++: ToAirplaneInfo()
group For each airplanes in the airport
    Airplane -> AirplaneInfo ++: new AirplaneInfo(string id, string name, AirplaneType type, int speed, int maintenanceTime)
    return AirplaneInfo
end
return List<AirplaneInfo>
return List<AirplaneInfo>
return List<AirplaneInfo>

'Update View
Generator -> FormGenerator ++: UpdateAirplanes(List<AirplaneInfo> airplanes)
return
return
return

FormGenerator -> FormGenerator ++: listAirplanes_SelectedIndexChanged(object sender, EventArgs e)
return
return

@enduml