@startuml Loop in simulator
title A loop with too much event in the simulator
'hello jp
loop for each Tick
Simulator -> Simulator ++: CanGenerate()
return false
Simulator -> Simulator ++: UpdateEvents()
Simulator -> Scenario ++: Action(int time)
    loop for each Airport
        Scenario -> Airport ++: Action(int time)
        loop for each Airplane
            group if airplane is a FightPlane
                Airport -> FightPlane ++: Action(int time)
                FightPlane -> Fight ++: Action(int time)
                Fight -> EventFight ++: HandleEvent()
                EventFight -> Scenario ++: RemoveEvent()
                return 
                return
                return
                return
            end
            group if airplane is a ScoutPlane
                Airport -> ScoutPlane ++: Action(int time)
                ScoutPlane -> Scout ++: Action(int time)
                Scout -> EventScout ++: HandleEvent()
                return
                return
                return
            end
            group if airplane is a TransportPlane
                Airport -> TransportPlane ++: Action(int time)
                TransportPlane -> Transport ++: Action(int time)
                Transport -> EventClient ++: HandleEvent()
                EventFight -> Scenario ++: RemoveEvent()
                return
                return
                return
                return
            end
        end
    end
return


end


@enduml