@startuml Loop in simulator
title A loop with too much event in the simulator
'hello jp
loop for each Tick
Simulator -> Simulator ++: CanGenerate()
return false
Simulator -> Simulator ++: UpdateEvents()
Simulator -> Scenario ++: Action(int time)
    loop for each Airport
        Scenario -> Airport ++: Action(int time)
        loop for each Airplane
            Airport -> AirPlane ++: Action(int time)
            AirPlane -> State ++: Action(int time)
            State -> Event ++: HandleEvent()
            Event -> Scenario ++: RemoveEvent()
            return
            return
            State -> State ++: ChangeState()
            State -> State ++: Action(int time)
            return
            return
            return
            return
            
            /'group if airplane is a FightPlane
                Airport -> FightPlane ++: Action(int time)
                FightPlane -> Fight ++: Action(int time)
                Fight -> EventFight ++: HandleEvent()
                EventFight -> Scenario ++: RemoveEvent()
                
                return 
                return
                return
                return
            end
            group if airplane is a ScoutPlane
                Airport -> ScoutPlane ++: Action(int time)
                ScoutPlane -> Scout ++: Action(int time)
                Scout -> EventScout ++: HandleEvent()
                return
                return
                return
            end
            
            group if airplane is a TransportPlane
                Airport -> TransportPlane ++: Action(int time)
                TransportPlane -> Transport ++: Action(int tim)
                Transport -> EventClient ++: HandleEvent()
                EventClient -> Scenario ++: RemoveEvent()
                return
                return
                Transport -> Transport ++: ChangeState(int time)
                return
                return
                return
                
            end
            group if airplane is a RescuePlane
               Airport -> RescuePlane ++: Action(int time)
               RescuePlane -> Rescue ++: Action(int time)
               Rescue -> EventRescue ++: HandleEvent()
               return
               return
               return
            end
            '/
        end
        return
    end
end


@enduml